import { Casino, Category, Bonus, BlogPost } from './types';

export const CATEGORIES: Category[] = [
  { id: 'online-casinos', name: 'Online Casinos', icon: 'Layout', linkCount: 42 },
  { id: 'live-casino', name: 'Live Casino', icon: 'Video', linkCount: 28 },
  { id: 'slot-games', name: 'Slot Games', icon: 'Dices', linkCount: 56 },
  { id: 'sports-betting', name: 'Sports Betting', icon: 'Trophy', linkCount: 15 },
  { id: 'poker', name: 'Poker', icon: 'Spade', linkCount: 12 },
  { id: 'lottery', name: 'Lottery', icon: 'Ticket', linkCount: 8 },
  { id: 'crypto-casinos', name: 'Crypto Casinos', icon: 'Bitcoin', linkCount: 24 },
  { id: 'mobile-apps', name: 'Mobile Apps', icon: 'Smartphone', linkCount: 19 },
];

export const CASINOS: Casino[] = [
  {
    id: 'platinum-casino',
    name: 'Platinum Casino',
    logo: 'https://picsum.photos/seed/platinum/200/200',
    rating: 4.9,
    welcomeBonus: '100% Welcome Bonus up to RM1,500 + 100 Free Spins',
    visitUrl: 'https://example.com/platinum',
    bonusUrl: 'https://example.com/platinum-bonus',
    license: 'PAGCOR',
    categories: ['online-casinos', 'live-casino', 'slot-games'],
    description: 'Platinum Casino is Malaysia\'s most trusted platform, offering a premium gaming experience with lightning-fast withdrawals and 24/7 VIP support.',
    pros: ['Fastest withdrawals in MY', 'Exclusive VIP program', 'Huge slot variety'],
    cons: ['Higher wagering on some bonuses'],
    paymentMethods: ['DuitNow', 'Touch \'n Go', 'Bank Transfer', 'USDT'],
    isFeatured: true,
  },
  {
    id: 'gold-spin',
    name: 'Gold Spin',
    logo: 'https://picsum.photos/seed/gold/200/200',
    rating: 4.7,
    welcomeBonus: '150% Slot Bonus up to RM888',
    visitUrl: 'https://example.com/goldspin',
    bonusUrl: 'https://example.com/goldspin-bonus',
    license: 'Curacao',
    categories: ['slot-games', 'mobile-apps'],
    description: 'Specializing in the latest slot titles and mobile gaming, Gold Spin offers a seamless experience for players on the go.',
    pros: ['Optimized mobile app', 'Daily slot tournaments'],
    cons: ['Limited live dealer tables'],
    paymentMethods: ['DuitNow', 'Bank Transfer'],
    isNew: true,
  },
  {
    id: 'mega-win-88',
    name: 'Mega Win 88',
    logo: 'https://picsum.photos/seed/mega/200/200',
    rating: 4.5,
    welcomeBonus: 'RM50 Free Credit for New Members',
    visitUrl: 'https://example.com/megawin',
    bonusUrl: 'https://example.com/megawin-bonus',
    license: 'Malta Gaming Authority',
    categories: ['online-casinos', 'poker', 'lottery'],
    description: 'A veteran in the Malaysian market, Mega Win 88 is known for its reliability and extensive lottery options.',
    pros: ['Trusted for over 10 years', 'Great lottery odds'],
    cons: ['Website design feels slightly dated'],
    paymentMethods: ['Bank Transfer', 'Help2Pay'],
  },
  {
    id: 'crypto-bet',
    name: 'Crypto Bet',
    logo: 'https://picsum.photos/seed/crypto/200/200',
    rating: 4.8,
    welcomeBonus: '1 BTC Welcome Package',
    visitUrl: 'https://example.com/cryptobet',
    bonusUrl: 'https://example.com/cryptobet-bonus',
    license: 'Curacao',
    categories: ['crypto-casinos', 'sports-betting'],
    description: 'The leading cryptocurrency casino in Malaysia, supporting over 20 different coins with instant anonymous play.',
    pros: ['Instant crypto withdrawals', 'No KYC required'],
    cons: ['No fiat payment options'],
    paymentMethods: ['BTC', 'ETH', 'USDT', 'LTC'],
  }
];

export const BONUSES: Bonus[] = [
  {
    id: 'b1',
    casinoId: 'platinum-casino',
    casinoName: 'Platinum Casino',
    casinoLogo: 'https://picsum.photos/seed/platinum/100/100',
    title: '100% Welcome Bonus up to RM1,500',
    code: 'WELCOME100',
    wagering: '25x',
    url: 'https://example.com/platinum-bonus',
    type: 'Welcome',
  },
  {
    id: 'b2',
    casinoId: 'gold-spin',
    casinoName: 'Gold Spin',
    casinoLogo: 'https://picsum.photos/seed/gold/100/100',
    title: '150% Slot Special Bonus',
    code: 'SLOT150',
    wagering: '18x',
    url: 'https://example.com/goldspin-bonus',
    type: 'Reload',
  },
  {
    id: 'b3',
    casinoId: 'mega-win-88',
    casinoName: 'Mega Win 88',
    casinoLogo: 'https://picsum.photos/seed/mega/100/100',
    title: 'RM50 Free Credit - No Deposit',
    wagering: '1x',
    url: 'https://example.com/megawin-bonus',
    type: 'No Deposit',
  }
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'p1',
    title: 'How to Choose a Safe Online Casino in Malaysia',
    excerpt: 'With so many options available, finding a trustworthy platform is crucial. Here are the top 5 things to look for.',
    date: 'April 1, 2026',
    author: 'Admin',
    image: 'https://picsum.photos/seed/blog1/800/400',
  },
  {
    id: 'p2',
    title: 'Understanding Casino Bonuses: Wagering Requirements Explained',
    excerpt: 'Don\'t be fooled by big numbers. Learn how to calculate the real value of a casino bonus.',
    date: 'March 28, 2026',
    author: 'Expert Player',
    image: 'https://picsum.photos/seed/blog2/800/400',
  },
  {
    id: 'p3',
    title: 'Platinum Casino Review: Why It\'s #1 in 2026',
    excerpt: 'A deep dive into the features, games, and support that make Platinum Casino stand out.',
    date: 'March 25, 2026',
    author: 'Staff Writer',
    image: 'https://picsum.photos/seed/platinum/800/400',
    isSponsored: true,
  }
];
